wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673215267.425028
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.8
      5: 0.13.7
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: KNN
splitter:
  desc: null
  value: RandSplit
transformer:
  desc: null
  value: Identity
